### ISSUE TITLE
Rdf out not being prefixed

### ISSUE THREAD

**Issue by quintonn** [AcandoNorway/XmlToRdf#33]
I am testing the sample as per your readme file and i get weird looking output.

This is my output:

		_:1 <http://example.org#name> """Hello""" .
		_:1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org#item>.
		_:0 <http://acandonorway.github.com/XmlToRdf/ontology.ttl#hasChild> _:1.
		_:3 <http://example.org#name> """Hello""" .
		_:3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org#item>.
		_:0 <http://acandonorway.github.com/XmlToRdf/ontology.ttl#hasChild> _:3.
		_:0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org#data>.

And this is my code:

		public class App {
		
			public static void main(String[] args) {
				System.out.println("Hello World!");
				convertXmlToTurtleTest();
			}

			private static void convertXmlToTurtleTest() {
				try {
					BufferedInputStream in = new BufferedInputStream(new FileInputStream("data.xml"));
					BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream("data.ttl"));

					Builder.getAdvancedBuilderStream().build().convertToStream(in, out);

				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}

Why don't I get those nice prefixes you get?

Do i need to pass a flag somewhere?

**Comment by hmottestad** [comment]
You can try the Advanced Jena Builder instead - this gives you a Jena model that you can call write(...) on to output. 

```
Dataset dataset = Builder.getAdvancedBuilderJena().build().convertToDataset(in);
```

This sacrifices a fair bit of memory and performance. The Advanced Builder Stream is fully stream based and output the RDF as N-triples (since regular turtle is hard to stream). N-triples doesn't support prefixes.

**Comment by hmottestad** [comment]
Correction. You can call `getDefaultModel()` to get a model that you can then output by calling `write(OutputStream out, String lang)`
